#!/bin/bash

# Downloading .vimrc if necessary 
if [ ! -d ~/dotfiles ]; then
  echo 'dotfiles directory not found! Downloading .vimrc directly to '$HOME
  curl https://raw.githubusercontent.com/adrianovalente/dotfiles/master/vimrc.vim > ~/.vimrc
else
  echo 'Linking vimrc.symlink to home...'
  cp ~/dotfiles/vimrc.vim ~/.vimrc
fi

# Installing Pathogen
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

function install_plugin {
  local plugin_path="$HOME/.vim/bundle/$(echo $1 | cut -d/ -f5 | cut -d. -f1)"
  echo $plugin_path
  if [ ! -d $plugin_path ]; then
    git clone $1 $plugin_path
  else
    git -C $plugin_path pull
  fi
}

# Installing Exstentions
install_plugin https://github.com/ctrlpvim/ctrlp.vim.git
install_plugin https://github.com/scrooloose/nerdtree.git
install_plugin https://github.com/flazz/vim-colorschemes.git
install_plugin https://github.com/tpope/vim-fugitive.git
install_plugin https://github.com/romgrk/winteract.vim.git
install_plugin https://github.com/vim-syntastic/syntastic.git
install_plugin https://github.com/altercation/vim-colors-solarized.git
install_plugin git://github.com/airblade/vim-gitgutter.git

# Clojure/JVM Extensions
install_plugin https://github.com/tpope/vim-classpath.git
install_plugin https://github.com/guns/vim-clojure-static
install_plugin https://github.com/kien/rainbow_parentheses.vim
install_plugin https://github.com/tpope/vim-fireplace.git
