#!/bin/bash

echo 'Pulling .dotfiles from master...'
git -C $HOME/dotfiles pull > /dev/null

echo 'Rewriting system dotfiles...'
ls | grep dotfile | sed -e 's/.dotfile//g' | xargs -I {} sh -c 'cp {}.dotfile ~/.{}'

echo 'Loading vim...'
$HOME/dotfiles/setup-vim

if [ -d $HOME/.oh-my-zsh ]; then
  echo 'Updating oh-my-zsh custom configs...'
  rm -rf ~/.oh-my-zsh/custom
  cp -R ~/dotfiles/oh-my-zsh/custom ~/.oh-my-zsh
fi

exec $SHELL
