#!/bin/bash

function spotify_playing () {
  if [[ $(osascript -e 'tell application "Spotify" to player state as string' 2> /dev/null) == *"playing"* ]]; then
    artist=`osascript -e 'tell application "Spotify" to artist of current track as string' 2> /dev/null`;
    track=`osascript -e 'tell application "Spotify" to name of current track as string' 2> /dev/null`;
    echo " "$track" ("$artist")"
  fi
}
