#!/bin/bash

function spotify_playing() {
  [[ -n "$BYPASS_SPOTIFY_PLAYING" ]] && return
  osascript <<'EOF' 2>/dev/null
tell application "System Events"
    if not (exists process "Spotify") then
        return ""
    end if

end tell
tell application "Spotify"
    if player state is playing then
        return " " & name of current track & " (" & artist of current track & ")"
    end if
end tell
EOF
}

function spotify_prompt_off() {
  export BYPASS_SPOTIFY_PLAYING=1
}

function spotify_prompt_on() {
  unset BYPASS_SPOTIFY_PLAYING
}
